name: Check Existence of Required Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_req_files:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu

    steps:
    - name: Fetch Repo Code
      uses: actions/checkout@v2  

    - name: Check required files
      run: |
        GREEN='\033[0;32m'  # Green for passed
        RED='\033[0;31m'    # Red for failed

        # List of required files
        required_files=("ability.py" "arena.py" "armor.py" "hero.py" "main.py")
        all_passed=true
        
        echo -e "[FILES]:"

        # Loop through each file in the list and check if it exists
        for file in "${required_files[@]}"; do
          if [ -f "$file" ]; then
            echo -e "  • $file was submitted: ${GREEN}passed"
          else
            echo -e "  • $file was not submitted: ${RED}failed"
            all_passed=false 
          fi
        done


        if [ "$all_passed" = false ]; then
          echo -e "${RED}Some required files are missing. Please submit all files."
          exit 1  # Fail the job if any required file is missing
        fi

        echo -e "${GREEN}All required files are present. Proceeding with other checks."
    - name: File functionality
      run: |
        echo "This step can be used to run tests or checks on the files if needed."
        python3 arena.py
        