name: CI - Grading Lab3 Assignment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/upload-artifact@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Optional, if you have any extra dependencies

      - name: Run tests
        run: |
          python -m unittest test_lab3.py  # Run the grading script

      - name: Upload results (optional)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_lab3.py

# test